<script lang="ts">
	import {getCookie, setCookie, signIn} from "../../stores/auth";
	import {game_socket, user} from "../../stores/store";
	import {push} from "svelte-spa-router";
	import Modal, {getModal} from "../Profile/Modal.svelte";
	import { authenticate_2fa_code } from "../../stores/requests";

	let login: string;
	let password: string;
	let error: string;
	let twoFA_msg: string = undefined;

	async function simple_login() {
		const resp = await signIn(login, password);
		error = resp.message;

		// Failed login
		if (error) {
			return;
		}
		// No TwoFA and successful login
		else if (!resp.TwoFA) {
			$user = await $user.upd();
			await push("/");
		} else {
			getModal("sign-in-2fa").open();
		}
	}

	async function TwoFA_login(e) {
		// send access code to backend to validate 2FA activation

		const formData = new FormData(e.target);
		const code = formData.get("code").toString();
		if (code.length != 6) {
			twoFA_msg = `<p class="text-danger">The access code should be 6-digit long</p>`;
			return;
		}

		if (parseInt(code) < 0) {
			twoFA_msg = `<p class="text-danger">The access code should be a positive integer</p>`;
			return;
		}
		const authentication = await authenticate_2fa_code(login, code);
		twoFA_msg = authentication.message;
		if (authentication.success) {
			getModal("sign-in-2fa").close();
			$user = await $user.upd();
			await $game_socket.emit('update-user-data', getCookie('jwt'));
			await push("/");
		}
	}
</script>

<main>
    <form on:submit|preventDefault={simple_login}>
        <div class="mb-	md-5 mt-md-4 pb-5">
            <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
            <p class="text-white-50 mb-5">
                Please enter your login and password
            </p>
            <div class="form-outline form-white mb-4">
                <input
                        type="text"
                        id="typeTextX"
                        class="form-control form-control-lg"
                        required
                        bind:value={login}
                />
                <label class="form-label" for="typeTextX">Login</label>
            </div>
            <div class="form-outline form-white mb-4">
                <input
                        type="password"
                        id="typePasswordX"
                        class="form-control form-control-lg"
                        required
                        bind:value={password}
                />
                <label class="form-label" for="typePasswordX">Password</label>
            </div>

            {#if error !== undefined}
                <p class="text-danger">{error}</p>
            {/if}

            <button class="btn btn-outline-light btn-lg px-5" type="submit">
                Login
            </button
            >
        </div>
    </form>

    <!-- the pop-up for 2FA -->
    <Modal id="sign-in-2fa">
        <p class="p-2">
            Hey! You have activated the <strong
        >two-factor authentication on your account</strong
        >.
            <br/>Please enter the 6-digit access code generated by Google
            Authenticator:
        </p>
        <div
                class="d-flex flex-column justify-content-center align-content-center"
        >
            <div>
                <form
                        class="form-inline"
                        on:submit|preventDefault={TwoFA_login}
                >
                    <label class="sr-only" for="code">Access code</label>
                    <input
                            class="form-control mb-2 mr-sm-2 w-75"
                            type="number"
                            name="code"
                            id="code"
                            placeholder="Your access code"
                    />

                    <button type="submit" class="btn btn-dark mb-2"
                    >Submit
                    </button
                    >
                </form>
            </div>
            {#if twoFA_msg}
                {@html twoFA_msg}
            {/if}
        </div>
    </Modal>
</main>
