version: '3.1'


############### DOCKERS ##################
services:

## PostgreSQL database ##
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    networks:
      - network
    volumes:
      # - /goinfre/${USER}/data/postgres:/var/lib/postgresql/data
      - /goinfre/${USER}/data:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./config/postgres.env

## Database administration (pgAdmin) ##
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - '5050:80'
  #   volumes:
  #   - /goinfre/${USER}/data/pgadmin:/root/.pgadmin
  #   env_file:
  #   - ./config/postgres.env
  #   restart: always
  #   networks:
  #     - network
  #   depends_on:
  #     - postgres

## Backend (nestJS) ##

  backend:
    container_name: backend
    image: backend:ping_me_more
    build:
      context: backend/
    networks:
      - network
    restart: always
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - ./config/backend.env

############### NETWORKS ##################

networks:
  network: