version: '3.1'


############### DOCKERS ##################
services:

## PostgreSQL database ##
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    networks:
      - network
    volumes:
      - /goinfre/${USER}/data1:/var/lib/postgresql/data
      # - /Users/amyroshn/Documents/data:/var/lib/postgresql/data #ANTON PC
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./config/postgres.env

## Database administration (Adminer) ##
  adminer:
    container_name: adminer
    image: adminer:4
    ports:
      - '8080:8080'
    restart: always
    networks:
      - network
    depends_on:
      - postgres

## Backend (nestJS) ##

  backend:
    container_name: backend
    image: backend:ping_me_more
    build:
      context: backend/
    networks:
      - network
    restart: always
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - ./config/backend.env

## Frontend (Svelte) ##

  frontend:
    container_name: frontend
    build: frontend/
    image: frontend
    networks:
      - network
    restart: always
    depends_on:
      - backend
    ports:
      - '9000:9000'

############### NETWORKS ##################

networks:
  network: