version: '3.1'


############### DOCKERS ##################
services:

## PostgreSQL database ##
  postgres:
    container_name: postgres
    image: postgres
    networks:
      - network
    # volumes:
    #   - database:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./config/postgres.env

# Backend (nestJS)

  backend:
    container_name: backend
    image: backend:ping_me_more
    build:
      context: backend/
    networks:
      - network
    restart: always
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - ./config/backend.env

############### NETWORKS ##################

networks:
  network:


############### VOLUMES ##################

# volumes:
#   database:
#     driver_opts:
#       type: none
#       device: ./data
#       o: bind